### ISSUE TITLE
Unexpected results in 4.1 A Hello World Example?

### ISSUE THREAD

**Issue by kentjones** [rulebook-rules/rulebook#90] opened 2017-09-11 05:47 UTC
[hellowordrule.txt](https://github.com/rulebook-rules/rulebook/files/1291487/hellowordrule.txt)
[example4.1.txt](https://github.com/rulebook-rules/rulebook/files/1291469/example4.1.txt)
Hi Clayton,

Running the Hello World example using bogus facts the rulebook.getResults().isPresent() is true. Should the results be false? I was expecting a Null value.  

Running the Hello World example using RuleBookBuilder using bogus facts the rulebook.getResults().isPresent() is false. Which is what I expected. 

Love the RuleBook. Keep up the good work.

cheers,
Kent

**Comment by Clayton7510** [comment] 2017-09-12 02:48
Kent,

The RuleBookRunner that decorates a RuleBook and allows POJO Rule packages to be used as RuleBooks, essentially creates an empty Result. The reason why it does that is so Results can be injected into POJO Rules. If there is no Result, then it can't very well be chained.

However, just because there is a good reason for why Results with POJO rules always exist, doesn't make that good expected behavior. So, I think you're right that this is something which should be corrected. I'll tag it as a bug and look at getting this corrected. Thanks for bringing this up!

Thanks,

Clayton

**Comment by Clayton7510** [comment] 2017-09-13 00:26
The fix is in 0.8.1-SNAPSHOT now. I haven't put in tests for it yet. And as always, use SNAPSHOTs at your own risk. But all of the existing unit tests work - and I'm 90% sure it covered all the cases. I'll add some tests in sometime soon and probably push a patch release this weekend.

**Comment by Clayton7510** [comment] 2017-09-17 01:19
This was fixed in v0.8.1, now pushed to Maven Central.

**Closed by Clayton7510** 2017-09-17 01:19 UTC
Labels: bug, resolved pending confirmation
